#ifndef data_worlds_hpp
#define data_worlds_hpp

// defines (BIT7 for inpassable objects, BIT6 for interactive objects)
#define EMPTY 0x00
#define WALLTOP 0x81
#define WALLBOTTOM 0x82
#define WALLLEFT 0x83
#define WALLRIGHT 0x84
#define WALLCORNERTOPLEFT 0x85
#define WALLCORNERTOPRIGHT 0x86
#define WALLCORNERBOTTOMLEFT 0x87
#define WALLCORNERBOTTOMRIGHT 0x88

#define WEAPONSWORD 0x040

static const uint8_t cWorlddata[][16] = {
  //{
    {WALLCORNERTOPLEFT,WALLTOP,WALLTOP,WALLTOP,WALLTOP,WALLTOP,WALLTOP,WALLTOP,WALLTOP,WALLTOP,WALLTOP,WALLTOP,WALLTOP,WALLTOP,WALLTOP,WALLCORNERTOPRIGHT},
    {WALLLEFT,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WALLRIGHT},
    {WALLLEFT,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WALLRIGHT},
    {WALLLEFT,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WALLRIGHT},
    {WALLLEFT,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WALLRIGHT},
    {WALLLEFT,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WALLRIGHT},
    {WALLLEFT,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WALLRIGHT},
    {WALLCORNERBOTTOMLEFT,WALLBOTTOM,WALLBOTTOM,WALLBOTTOM,WALLBOTTOM,WALLBOTTOM,WALLBOTTOM,WALLBOTTOM,WALLBOTTOM,WALLBOTTOM,WALLBOTTOM,WALLBOTTOM,WALLBOTTOM,WALLBOTTOM,WALLBOTTOM,WALLCORNERBOTTOMRIGHT}
  //}
};

#endif // data_worlds_hpp
